# Build settings
gems:
  - jemoji
  - jekyll-paginate

# Site settings
title: "Reflections | Projections"
description: > # this means to ignore newlines until "email:"
   Reflections | Projections is an annual technology conference organized and run by students at the University of Illinois at Urbana-Champaign, drawing students, speakers, and companies from around the world. 
   Checkout what we've been up to!

future: true

email: conference-chair@acm.illinois.edu
#blog logo
logo: "/assets/images/logo.png"

# blog cover
cover: "/assets/images/cover.jpg"

name: 'Reflections | Projections Staff'
author: 'Reflections | Projections Staff'
author_image: "/assets/images/logo.png"

paginate:	5

url: "http://blog.acmrp.org" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
twitter_handle: '@uiuc_rp'

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

#google_analytics: UA-XXXXX-X

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/uiuc_rp
    desc: Follow us on Twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

  - icon:	instagram
    url:	https://www.instagram.com/uiuc_rp/
    desc: Follow us on Instagram

  - icon:	facebook
    url:	https://facebook.com/acmrp
    desc: Connect with us on Facebook
    share_url: https://www.facebook.com/sharer.php
    share_title: ?t=
    share_link: "&amp;u="

  # - icon:	github
  #   url:	https://github.com/hackillinois
  #   desc:	Check us out on GitHub
  #   share_url:
  #   share_title:
  #   share_link:
